##### FENÊTRE PRINCIPALE #####

# Damier
NB_LIGNES, NB_COLONNES = 8, 8

# Fenêtre
LARGEUR = 100*NB_COLONNES
HAUTEUR = 100*NB_LIGNES

# Couleurs
COULEUR_DAMIER1, COULEUR_DAMIER2 = "#DAB790", "#9D551E"
COULEUR_PIECE1 = "black"
COULEUR_CASE_ACTIVE = "#26C479"
COULEUR_COUP_POSSIBLE1, COULEUR_COUP_POSSIBLE2 = "#4FC7E3", "#3A4FEA"
COULEUR_INFOS, COULEUR_INFOS_FIN_JEU, COULEUR_FOND_INFOS = "black", "red", "#F0F0F0"

##### FENÊTRE PROMOTION #####

NB_TYPES_PIECES = 4
NB_LIGNES_PROMOTION = 1

# Fenêtre
LARGEUR_PROMOTION = 100*NB_TYPES_PIECES
HAUTEUR_PROMOTION = 100
