from view import NB_LIGNES, NB_COLONNES, LARGEUR, HAUTEUR, COULEUR_CASE_ACTIVE, COULEUR_COUP_POSSIBLE1, \
                 COULEUR_COUP_POSSIBLE2, COULEUR_INFOS, COULEUR_INFOS_FIN_JEU, COULEUR_FOND_INFOS, NB_TYPES_PIECES, \
                 LARGEUR_PROMOTION, HAUTEUR_PROMOTION
